In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from six.moves import urllib

import warnings
warnings.filterwarnings('ignore')

import os

In [ ]:
data_dir = './data/'
os.makedirs(data_dir, exist_ok=True)
data_url = "https://raw.githubusercontent.com/mohitmahiyt/cardataset/refs/heads/main/cars_dataset.csv"

filename = os.path.basename(data_url)

filepath = os.path.join(data_dir, filename)

urllib.request.urlretrieve(data_url, filepath)
print("file downloaded successfully")

file downloaded successfully

In [25]:
df = pd.read_csv("./data/customer_data.csv")

In [26]:
df

,pages_viewed,time_spent_sec,previous_visits,products_viewed,added_to_cart,device_type,previous_purchases,purchase
0,NaN,70.9,1.0,1.0,0.0,tablet,2.0,1.0
1,5.0,NaN,2.0,2.0,0.0,desktop,2.0,0.0
2,5.0,207.1,1.0,1.0,0.0,desktop,2.0,0.0
3,6.0,71.2,2.0,6.0,0.0,desktop,1.0,1.0
4,6.0,19.5,1.0,3.0,1.0,mobile,1.0,0.0
...,...,...,...,...,...,...,...,...
4995,3.0,22.3,0.0,2.0,0.0,desktop,1.0,0.0
4996,5.0,32.4,0.0,7.0,0.0,desktop,1.0,0.0
4997,8.0,68.6,3.0,3.0,1.0,mobile,2.0,1.0
4998,7.0,215.3,4.0,2.0,1.0,mobile,2.0,1.0
4999,4.0,300.1,3.0,7.0,0.0,mobile,1.0,1.0

In [27]:
df.head(20)

,pages_viewed,time_spent_sec,previous_visits,products_viewed,added_to_cart,device_type,previous_purchases,purchase
0,NaN,70.9,1.0,1.0,0.0,tablet,2.0,1.0
1,5.0,NaN,2.0,2.0,0.0,desktop,2.0,0.0
2,5.0,207.1,1.0,1.0,0.0,desktop,2.0,0.0
3,6.0,71.2,2.0,6.0,0.0,desktop,1.0,1.0
4,6.0,19.5,1.0,3.0,1.0,mobile,1.0,0.0
5,4.0,135.8,2.0,2.0,1.0,tablet,2.0,1.0
6,6.0,74.5,1.0,7.0,1.0,mobile,1.0,1.0
7,5.0,273.6,0.0,1.0,0.0,desktop,0.0,0.0
8,7.0,152.0,4.0,2.0,0.0,mobile,1.0,0.0
9,8.0,264.NaN,2.0,6.0,0.0,desktop,2.0,1.0
10,3.0,173.2,NaN,2.0,0.0,mobile,2.0,1.0
11,6.0,210.9,0.0,2.0,1.0,mobile,1.0,1.0
12,6.0,130.5,3.0,1.0,0.0,tablet,3.0,0.0
13,7.0,181.2,3.0,2.0,0.0,desktop,0.0,0.0
14,5.0,49.8,1.0,3.0,0.0,mobile,0.0,0.0
15,7.0,172.NaN,1.0,5.0,0.0,desktop,2.0,0.0
16,7.0,30.0,2.0,2.0,0.0,mobile,0.0,0.0
17,2.0,94.9,3.0,4.0,0.0,mobile,3.0,0.0
18,8.0,62.2,0.0,2.0,0.0,desktop,0.0,0.0
19,3.0,120.1,2.0,4.0,0.0,tablet,2.0,0.0

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   pages_viewed        4997 non-null   float64
 1   time_spent_sec      4999 non-null   object
 2   previous_visits     4997 non-null   float64
 3   products_viewed     4999 non-null   float64
 4   added_to_cart       4999 non-null   float64
 5   device_type         5000 non-null   object
 6   previous_purchases  4999 non-null   float64
 7   purchase            4999 non-null   float64
dtypes: float64(6), object(2)
memory usage: 312.6+ KB

In [29]:
df.isnull().sum()

pages_viewed          3
time_spent_sec        1
previous_visits       3
products_viewed       1
added_to_cart         1
device_type           0
previous_purchases    1
purchase              1
dtype: int64

In [30]:
df[df.isna().all(axis=1)]

Empty DataFrame
Columns: [pages_viewed, time_spent_sec, previous_visits, products_viewed, added_to_cart, device_type, previous_purchases, purchase]
Index: []

In [31]:
df.dropna(how='all', inplace=True)

In [32]:
df.isnull().sum()

pages_viewed          3
time_spent_sec        1
previous_visits       3
products_viewed       1
added_to_cart         1
device_type           0
previous_purchases    1
purchase              1
dtype: int64

In [34]:
df.reset_index(drop=True,inplace=True)

In [39]:
df.columns

Index(['pages_viewed', 'time_spent_sec', 'previous_visits', 'products_viewed',
       'added_to_cart', 'device_type', 'previous_purchases', 'purchase'],
      dtype='object')

In [40]:
df.duplicated().sum()

np.int64(1)

In [41]:
df[df.duplicated(keep=False)]

,pages_viewed,time_spent_sec,previous_visits,products_viewed,added_to_cart,device_type,previous_purchases,purchase
16,7.0,30.0,2.0,2.0,0.0,mobile,0.0,0.0
3759,7.0,30.0,2.0,2.0,0.0,mobile,0.0,0.0

In [42]:
df.drop_duplicates(inplace=True)